---
- name: SAP Hana cluster
  hosts: hana
  remote_user: cloudadmin
  become: true
  become_user: root
  vars:
    # SAPHahaSR-angi
    use_hana_sr_angi: "{{ use_sap_hana_sr_angi | default(false) }}"
    # is_primary is selected so that tasks that need to be issued one are honoured correctly
    is_primary: "{{ ansible_play_hosts[0] == inventory_hostname }}"
    primary_hostname: "{{ ansible_play_hosts[0] }}"
    # Azure fencing specific vars
    azure_identity_management:  # use 'spi' (service principal) or 'msi' (managed identity)
    # Azure fencing - SPN related variables
    spn_application_id:
    spn_application_password:
    # corosync variables
    crypto_hash: sha1
    crypto_cipher: aes256
    # Define some names in a central place
    rsc_socat: "rsc_socat_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"
    rsc_saphanactl: "rsc_SAPHanaCtl_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"
    ms_saphanactl: "msl_SAPHanaCtl_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"


  handlers:
    - name: Restart systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start pacemaker
      ansible.builtin.systemd:
        name: pacemaker
        state: started
        enabled: true

    - name: Write stonith status file
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        owner: root
        group: root
        mode: '0700'
      with_items:
        - {'path': '/var/lib/qedep', 'state': 'directory'}
        - {'path': '/var/lib/qedep/sbd', 'state': 'touch'}

  pre_tasks:
    - name: Detect cloud platform
      ansible.builtin.include_tasks:
        ./tasks/detect-cloud-platform.yaml

    - name: Load SAP HANA variables
      ansible.builtin.include_vars: ./vars/hana_vars.yaml

    - name: Re-set HANA Angi vars
      ansible.builtin.set_fact:
        ms_saphanactl: "mst_SAPHanaCtl_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"
      when:
        - use_hana_sr_angi | bool

  tasks:
    - name: Base Cluster Configuration [azure]
      ansible.builtin.include_tasks: ./tasks/azure-cluster-bootstrap.yaml
      when: cloud_platform_is_azure
      tags: bootstrap

    - name: Base Cluster Configuration [aws]
      ansible.builtin.include_tasks: ./tasks/aws-cluster-bootstrap.yaml
      when: cloud_platform_is_aws
      tags: bootstrap

    - name: Base Cluster Configuration [gcp]
      ansible.builtin.include_tasks: ./tasks/gcp-cluster-bootstrap.yaml
      when: cloud_platform_is_gcp
      tags: bootstrap

    - name: Add HANA to cluster [azure]
      ansible.builtin.include_tasks: ./tasks/azure-cluster-hana.yaml
      when:
        - cloud_platform_is_azure
        - is_primary
      tags: hana_cluster

    - name: Add HANA to cluster [aws]
      ansible.builtin.include_tasks: ./tasks/cluster-hana.yaml
      when:
        - cloud_platform_is_aws
        - is_primary

    - name: Add HANA to cluster [gcp]
      ansible.builtin.include_tasks: ./tasks/cluster-hana.yaml
      when:
        - cloud_platform_is_gcp
        - is_primary

    - name: Refresh MS
      ansible.builtin.command:
        cmd: >-
          crm resource
          refresh
          {{ ms_saphanactl }}
      when: is_primary
      register: refresh_ms_result
      changed_when: refresh_ms_result.rc == 0

    - name: MS Resource Maintenance off
      ansible.builtin.command:
        cmd: >-
          crm resource
          maintenance
          {{ ms_saphanactl }}
          off
      when: is_primary
      register: maintenance_off_result
      changed_when: maintenance_off_result.rc == 0

    - name: Wait for cluster to settle
      ansible.builtin.command:
        cmd: cs_wait_for_idle -s 5
      when: is_primary
      changed_when: false
